Remove deprecated fields
aukaio/merchant-api-python-sdk pull request #3
Opened 2017-08-06 20:50 UTC by Jakob-Koschel

ledger field is deprecated in core therefore merchant-console doesn't work any more.

2017-08-06 20:50 UTC, Jakob-Koschel commented on mcash/mapi_client/mapi_client.py
> +        TODO change this text (any suggestions?)
Does anyone have input here? I don't know what this function does.

2017-08-06 20:51 UTC, Jakob-Koschel commented on mcash/mapi_client/mapi_client.py
> +        TODO change this text (any suggestions?)
Does anyone have input here? I don't know what this function does.

2017-08-07 07:15 UTC, leosobral requested changes
Remove ledger parts from comment

2017-08-07 08:28 UTC, leosobral approved these changes

2017-08-07 08:28 UTC, merged